-- AdBidCoin growth scout, referral attribution, and manual USDC reward ledger.
-- Run once in the Supabase SQL editor before enabling GROWTH_SCOUT_ENABLED.
-- All tables are server-only. No reward is paid automatically by this schema.

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table if not exists public.growth_opportunities (
  id bigint generated by default as identity primary key,
  source text not null,
  source_url text not null unique,
  title text not null,
  excerpt text not null default '',
  search_query text not null default '',
  relevance_score integer not null default 0
    check (relevance_score between 0 and 100),
  policy_risk text not null default 'manual_review'
    check (policy_risk in ('low', 'opt_in_only', 'manual_review', 'do_not_post')),
  status text not null default 'new'
    check (status in ('new', 'approved', 'published', 'dismissed')),
  draft_text text not null default '',
  telegram_message_id text not null default '',
  discovered_at timestamptz not null default now(),
  reviewed_at timestamptz,
  published_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz
);

create table if not exists public.referral_codes (
  id bigint generated by default as identity primary key,
  code text not null unique,
  label text not null,
  promoter_wallet text not null default '',
  reward_usdc numeric(12, 2) not null default 1
    check (reward_usdc >= 0 and reward_usdc <= 25),
  status text not null default 'active'
    check (status in ('active', 'paused', 'closed')),
  created_at timestamptz not null default now(),
  updated_at timestamptz
);

create table if not exists public.referral_visits (
  id bigint generated by default as identity primary key,
  referral_code text not null references public.referral_codes(code),
  visitor_hash text not null,
  landing_path text not null default '/',
  created_at timestamptz not null default now()
);

create table if not exists public.referral_conversions (
  id bigint generated by default as identity primary key,
  referral_code text not null references public.referral_codes(code),
  referred_wallet text not null unique,
  bid_id bigint not null unique references public.bids(id) on delete restrict,
  reward_usdc numeric(12, 2) not null check (reward_usdc >= 0),
  status text not null default 'pending'
    check (status in ('pending', 'approved', 'paid', 'rejected')),
  payout_signature text not null default '',
  converted_at timestamptz not null default now(),
  reviewed_at timestamptz,
  paid_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz
);

create index if not exists growth_opportunities_status_score_idx
  on public.growth_opportunities (status, relevance_score desc, discovered_at desc);

create index if not exists referral_visits_code_created_idx
  on public.referral_visits (referral_code, created_at desc);

create index if not exists referral_visits_hash_created_idx
  on public.referral_visits (visitor_hash, created_at desc);

create index if not exists referral_conversions_code_status_idx
  on public.referral_conversions (referral_code, status, converted_at desc);

drop trigger if exists growth_opportunities_set_updated_at
  on public.growth_opportunities;
create trigger growth_opportunities_set_updated_at
before update on public.growth_opportunities
for each row execute function public.set_updated_at();

drop trigger if exists referral_codes_set_updated_at
  on public.referral_codes;
create trigger referral_codes_set_updated_at
before update on public.referral_codes
for each row execute function public.set_updated_at();

drop trigger if exists referral_conversions_set_updated_at
  on public.referral_conversions;
create trigger referral_conversions_set_updated_at
before update on public.referral_conversions
for each row execute function public.set_updated_at();

comment on table public.growth_opportunities is
  'Review-first web discovery queue. The app never auto-replies or mass-messages.';
comment on table public.referral_visits is
  'Privacy-preserving campaign visits; stores a rotating HMAC identifier, never a raw IP address.';
comment on table public.referral_conversions is
  'First verified-bid referrals and a manual USDC reward ledger. No automatic custody or payout.';

alter table public.growth_opportunities enable row level security;
alter table public.referral_codes enable row level security;
alter table public.referral_visits enable row level security;
alter table public.referral_conversions enable row level security;

revoke all on table public.growth_opportunities from anon, authenticated;
revoke all on table public.referral_codes from anon, authenticated;
revoke all on table public.referral_visits from anon, authenticated;
revoke all on table public.referral_conversions from anon, authenticated;

grant select, insert, update, delete on table public.growth_opportunities to service_role;
grant select, insert, update, delete on table public.referral_codes to service_role;
grant select, insert, update, delete on table public.referral_visits to service_role;
grant select, insert, update, delete on table public.referral_conversions to service_role;
grant usage, select on all sequences in schema public to service_role;
