create table if not exists public.auctions (
  id text primary key,
  sequence bigint not null unique,
  starts_at bigint not null,
  ends_at bigint not null,
  status text not null default 'scheduled'
    check (status in ('live', 'scheduled', 'ended')),
  created_at timestamptz not null default now()
);

create table if not exists public.bids (
  id bigint generated by default as identity primary key,
  auction_id text not null references public.auctions(id) on delete cascade,
  wallet text not null,
  amount_usdc numeric(12, 2) not null check (amount_usdc > 0),
  payment_status text not null default 'verified'
    check (payment_status in ('verified', 'failed', 'pending')),
  payment_signature text,
  verification_provider text not null default 'solana-usdc',
  created_at timestamptz not null default now()
);

create table if not exists public.attention_content (
  id bigint generated by default as identity primary key,
  auction_id text not null unique references public.auctions(id) on delete cascade,
  wallet text not null,
  title text not null,
  description text not null default '',
  url text not null default '',
  image_url text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz
);

create index if not exists bids_auction_highest_idx
  on public.bids (auction_id, payment_status, amount_usdc desc, created_at asc);

create index if not exists bids_auction_recent_idx
  on public.bids (auction_id, payment_status, created_at desc);

create unique index if not exists bids_payment_signature_unique_idx
  on public.bids (payment_signature)
  where payment_signature is not null;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists attention_content_set_updated_at on public.attention_content;

create trigger attention_content_set_updated_at
before update on public.attention_content
for each row
execute function public.set_updated_at();

comment on table public.auctions is
  'Continuous 15-minute Attention Bid auction windows.';

comment on table public.bids is
  'USDC bids for upcoming attention blocks. Demo verification is used until real Solana confirmation is added.';

comment on table public.attention_content is
  'Winner-controlled homepage content for each attention block.';
