create table if not exists public.auctions (
  id text primary key,
  sequence bigint not null unique,
  starts_at bigint not null,
  ends_at bigint not null,
  status text not null default 'scheduled'
    check (status in ('live', 'scheduled', 'ended')),
  created_at timestamptz not null default now()
);

create table if not exists public.bids (
  id bigint generated by default as identity primary key,
  auction_id text not null references public.auctions(id) on delete cascade,
  wallet text not null,
  amount_usdc numeric(12, 2) not null check (amount_usdc > 0),
  quiet_balance numeric(30, 9) not null default 0,
  quiet_balance_slot bigint not null default 0,
  bid_multiplier numeric(12, 6) not null default 1,
  effective_bid_usdc numeric(24, 8) not null,
  payment_status text not null default 'verified'
    check (payment_status in ('verified', 'failed', 'pending')),
  payment_signature text,
  verification_provider text not null default 'solana-usdc',
  bid_source text not null default 'user'
    check (bid_source in ('user', 'house')),
  created_at timestamptz not null default now()
);

create table if not exists public.attention_content (
  id bigint generated by default as identity primary key,
  auction_id text not null unique references public.auctions(id) on delete cascade,
  wallet text not null,
  title text not null,
  description text not null default '',
  url text not null default '',
  image_url text not null default '',
  moderation_status text not null default 'pending',
  moderation_note text not null default '',
  reviewed_at timestamptz,
  reviewed_by text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz
);

create table if not exists public.attention_events (
  id bigint generated by default as identity primary key,
  auction_id text not null references public.auctions(id) on delete cascade,
  event_type text not null
    check (event_type in ('page_view', 'link_click')),
  wallet text not null default '',
  target_url text not null default '',
  created_at timestamptz not null default now()
);

alter table public.attention_content
  add column if not exists moderation_status text not null default 'pending';

alter table public.attention_content
  alter column moderation_status set default 'pending';

alter table public.attention_content
  add column if not exists moderation_note text not null default '';

alter table public.attention_content
  add column if not exists reviewed_at timestamptz;

alter table public.attention_content
  add column if not exists reviewed_by text not null default '';

alter table public.bids
  add column if not exists bid_source text not null default 'user';

alter table public.bids
  add column if not exists quiet_balance numeric(30, 9) not null default 0;

alter table public.bids
  add column if not exists quiet_balance_slot bigint not null default 0;

alter table public.bids
  add column if not exists bid_multiplier numeric(12, 6) not null default 1;

alter table public.bids
  add column if not exists effective_bid_usdc numeric(24, 8);

update public.bids
set effective_bid_usdc = amount_usdc
where effective_bid_usdc is null;

alter table public.bids
  alter column effective_bid_usdc set not null;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'bids_bid_source_check'
      and conrelid = 'public.bids'::regclass
  ) then
    alter table public.bids
      add constraint bids_bid_source_check
      check (bid_source in ('user', 'house'));
  end if;
end
$$;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'bids_quiet_balance_check'
      and conrelid = 'public.bids'::regclass
  ) then
    alter table public.bids
      add constraint bids_quiet_balance_check check (quiet_balance >= 0);
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'bids_bid_multiplier_check'
      and conrelid = 'public.bids'::regclass
  ) then
    alter table public.bids
      add constraint bids_bid_multiplier_check
      check (bid_multiplier >= 1 and bid_multiplier <= 10);
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'bids_effective_bid_usdc_check'
      and conrelid = 'public.bids'::regclass
  ) then
    alter table public.bids
      add constraint bids_effective_bid_usdc_check
      check (effective_bid_usdc > 0);
  end if;
end
$$;

drop index if exists public.bids_auction_highest_idx;

create index bids_auction_highest_idx
  on public.bids (
    auction_id,
    payment_status,
    bid_source,
    effective_bid_usdc desc,
    amount_usdc desc,
    created_at asc
  );

create index if not exists bids_auction_recent_idx
  on public.bids (auction_id, payment_status, created_at desc);

create unique index if not exists bids_payment_signature_unique_idx
  on public.bids (payment_signature)
  where payment_signature is not null;

create unique index if not exists bids_one_active_house_bid_per_auction_idx
  on public.bids (auction_id)
  where bid_source = 'house' and payment_status in ('pending', 'verified');

create index if not exists attention_content_moderation_status_idx
  on public.attention_content (moderation_status, updated_at desc, created_at desc);

create index if not exists attention_events_type_created_idx
  on public.attention_events (event_type, created_at desc);

create index if not exists attention_events_auction_type_idx
  on public.attention_events (auction_id, event_type);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists attention_content_set_updated_at on public.attention_content;

create trigger attention_content_set_updated_at
before update on public.attention_content
for each row
execute function public.set_updated_at();

comment on table public.auctions is
  'Continuous Attention Bid auction windows; production moved from 15 to 30 minutes in September 2026.';

comment on table public.bids is
  'Verified Solana USDC bids for upcoming attention blocks.';

comment on column public.bids.quiet_balance is
  'Server-verified QUIET balance snapshot used to calculate bid power.';

comment on column public.bids.bid_multiplier is
  'Linear QUIET bid multiplier snapshotted when the verified bid is recorded.';

comment on column public.bids.effective_bid_usdc is
  'USDC amount multiplied by bid_multiplier; used to rank user bids.';

comment on table public.attention_content is
  'Winner-controlled homepage content for each attention block, with admin moderation state.';

comment on table public.attention_events is
  'Page view and link click events for Attention Bid homepage metrics.';

alter table public.auctions enable row level security;
alter table public.bids enable row level security;
alter table public.attention_content enable row level security;
alter table public.attention_events enable row level security;

revoke all on table public.auctions from anon, authenticated;
revoke all on table public.bids from anon, authenticated;
revoke all on table public.attention_content from anon, authenticated;
revoke all on table public.attention_events from anon, authenticated;
revoke usage, select on all sequences in schema public from anon, authenticated;

grant select, insert, update, delete on table public.auctions to service_role;
grant select, insert, update, delete on table public.bids to service_role;
grant select, insert, update, delete on table public.attention_content to service_role;
grant select, insert, update, delete on table public.attention_events to service_role;
grant usage, select on all sequences in schema public to service_role;
